import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { buildCatalogue, caseFiles, SOURCE_COMMIT, SOURCE_REPOSITORY } from "./lib/showcase-data.mjs";

const repositoryRoot = path.resolve(import.meta.dirname, "..");
const outputDirectory = path.join(repositoryRoot, "src", "generated");
const definitions = await buildCatalogue(repositoryRoot);
const fileCount = (await caseFiles(repositoryRoot)).length;
const previewDataUrls = Object.fromEntries(
  definitions
    .filter((definition) => definition.preview?.resourceUri)
    .map((definition) => [definition.id, definition.preview.resourceUri]),
);
const generatedAt = "2026-08-29";
const serialized = JSON.stringify(definitions, null, 2)
  .replaceAll(" ", "\\u2028")
  .replaceAll(" ", "\\u2029");

const source = `// Generated by scripts/generate-catalog.mjs. Do not edit by hand.\n` +
  `import type { ShowcaseDefinition } from "../shared/types.js";\n\n` +
  `export const SHOWCASE_SOURCE = ${JSON.stringify({ repository: SOURCE_REPOSITORY, commit: SOURCE_COMMIT, generatedAt }, null, 2)} as const;\n\n` +
  `export const SHOWCASE_SOURCE_COMMIT = ${JSON.stringify(SOURCE_COMMIT)};\n` +
  `export const SHOWCASE_FILE_COUNT = ${fileCount};\n` +
  `export const PREVIEW_DATA_URLS: Record<string, string> = ${JSON.stringify(previewDataUrls, null, 2)};\n\n` +
  `export const SHOWCASES: ShowcaseDefinition[] = ${serialized};\n\n` +
  `export const SHOWCASE_BY_ID = new Map(SHOWCASES.map((showcase) => [showcase.id, showcase]));\n`;

await mkdir(outputDirectory, { recursive: true });
await writeFile(path.join(outputDirectory, "catalog.ts"), source, "utf8");
console.log(`Generated ${definitions.length} showcases from ${SOURCE_COMMIT.slice(0, 8)}.`);
